// Assembles site/ — the simulator, the generated report browsers, and a landing page
// listing them, ready for GitHub Pages.
//
//   node src/build_pages.js
//
// The simulator is already a static page with no build step, so this exists for one
// reason: it loads ../data/world-model-data.js, a path that reaches OUT of the
// directory it sits in. Publishing src/ alone would silently drop the world model and
// leave the page on the generated BA graph — it degrades rather than failing, which is
// the worst way for this to go wrong. The copy flattens that one path.
//
// Deliberately NOT publishing the whole repository root. That would work (the relative
// paths resolve as-is) but the entry point would be /src/simulator.html and every
// source file would be served alongside it. A handful of named files is a smaller thing
// to reason about.
//
// Layout, which differs from the repository's and is why two paths get rewritten here:
//
//   site/index.html            generated from src/landing.template.html
//   site/simulator.html        src/simulator.html, ../data/ paths flattened
//   site/report.html etc.      doc/*.html, simulatorHref repointed at simulator.html
//   site/data/, engine.js ...  copied as-is
//
// The reports are OPTIONAL: they are built from results/, which is not in the
// repository, so a fresh clone publishes the simulator alone rather than failing.
"use strict";
const fs = require("fs");
const path = require("path");
const paths = require("./paths.js");

const OUT = path.join(paths.ROOT, "site");

// [source, destination]. Destinations are flat except for data/, which is kept as a
// directory so the rewrite below is one path rather than several.
const ASSETS = [
  [paths.src("engine.js"), "engine.js"],
  [paths.src("network_view.js"), "network_view.js"],
  [paths.src("world_model.js"), "world_model.js"],
  [paths.data("world-model-data.js"), "data/world-model-data.js"],
  // The cell-code lookup behind simulator.html's applyScenarioCode() — typing "AI-482"
  // reproduces that heatmap cell. Generated by build_report.js, so it changes whenever
  // an experiment set is rebuilt; published rather than inlined for that reason.
  [paths.data("cell-index.js"), "data/cell-index.js"],
];

// The generated report browsers, published alongside the simulator. OPTIONAL, unlike
// everything above: they are built from results/ (2.1 GB of CSV that is not in the
// repository), so a fresh clone legitimately does not have them and must still be able
// to build the simulator. A missing one is a warning here, not an exit.
//
// Self-contained single files — no <script src>, no assets — so they are copied rather
// than assembled, and the orphan check below has nothing to say about them.
// `manifest` names the file the counts on the landing page are read from, so those
// figures cannot drift from the set they describe.
const REPORTS = [
  {
    src: path.join(paths.DOC, "report.html"), dest: "report.html",
    title: "AI parameter sweeps",
    manifest: "experiments.worldmodel.manifest.json",
    blurb: "Pairs of parameters varied against each other on a grid. Each cell is the mean "
      + "of repeated runs, measured as the difference from a run of the same seed with AI "
      + "disabled. Readable as a grid of colours or as a table of numbers.",
  },
  {
    src: path.join(paths.DOC, "structure_report.html"), dest: "structure_report.html",
    title: "Structure sweeps",
    manifest: "experiments.structure.manifest.json",
    blurb: "The same comparison, with the number of institutions and the shape of the "
      + "network between them on one axis instead of a second AI parameter.",
  },
  {
    src: path.join(paths.DOC, "results_ACL.html"), dest: "results_ACL.html",
    title: "Assisted-learning scenario set",
    manifest: "experiments.acl.manifest.json",
    blurb: "The same comparison run under three assumed sizes for the reported effect of "
      + "AI assistance on below-average performers, crossed with five values for its "
      + "effect on those above the threshold.",
  },
  {
    src: path.join(paths.DOC, "recruitment_report.html"), dest: "recruitment_report.html",
    title: "Recruitment shock",
    manifest: "experiments.recruitment.manifest.json",
    blurb: "A temporary hiring freeze applied to a field already at its equilibrium "
      + "distribution, crossed with freeze depth and duration and with each AI parameter "
      + "in turn.",
  },
  {
    src: path.join(paths.DOC, "entrant_report.html"), dest: "entrant_report.html",
    title: "Entrant expertise",
    manifest: "experiments.entrant.manifest.json",
    // What this set varies is the distribution REPLACEMENTS are drawn from at turnover,
    // not the t=0 population: engine.js keeps the two deliberately separate, since the
    // starting population represents an already-running mixed-skill field while entrants
    // arrive as genuine novices.
    //
    // The blurb says "not capped by what the people already there know", not "not inherited
    // from them". Teaching CREATES expertise — the update reads Teach[j] as a value and
    // debits nobody — so a conservation reading of it is wrong. What the taught and personal
    // channels are is CEILINGED, at min(aptitude, Teach) and at the institution's founding
    // average respectively. The entrant draw answers to neither, which is the property that
    // makes it the floor of the equilibrium distribution and the reason for this set.
    blurb: "What happens when the people replacing leavers arrive better or worse prepared. "
      + "Varies the mean, spread and lower bound of the distribution new arrivals are drawn "
      + "from at turnover — the one input to the model not capped by what the people already "
      + "there know — against each AI parameter in turn.",
  },
];

// Hand-written, self-contained pages committed to doc/. A different shape again from
// REPORTS above, and separate from it for two concrete reasons rather than tidiness: the
// REPORTS loop reads a "simulatorHref" out of each file's embedded DATA blob and exits if
// it is absent, and manifestFacts() needs a manifest in data/ — a written page has
// neither. They are also NOT optional the way the reports are: they do not come from
// results/, so a missing one means this list no longer matches the repository, which is a
// real error and not an absent build artifact.
const DOC_PAGES = [
  {
    src: path.join(paths.DOC, "capability_weight.html"), dest: "capability_weight.html",
    title: "Capability weight",
    blurb: "The function underneath every capability number on the pages above: w(E) = "
      + "\u03C1^((E\u2212\u03B8)/(1\u2212\u03B8)), which converts one person's expertise into "
      + "threshold-expert equivalents. Shows what somebody at the top of the distribution is "
      + "worth across every setting of the two constants, against the share of the population "
      + "sitting below the threshold at each one. Neither constant is measured against anything "
      + "external, and this is what they are worth at the top.",
  },
  {
    // GENERATED, unlike the page above, but committed for the same reason the reports are:
    // it is built from results/rho-trajectories/, which is not in the repository, so CI
    // cannot rebuild it and the only way the site can serve it is for the built file to be
    // committed. Rebuild with ./src/run_valuation_trajectories.sh.
    src: path.join(paths.DOC, "valuation_trajectories.html"), dest: "valuation_trajectories.html",
    title: "Valuation trajectories",
    blurb: "What the capability numbers do over three careers if ρ is taken from a published "
      + "valuation of fund-manager skill rather than assumed. PST and Barras each price a $400bn and "
      + "a $1.2Trn pool, and each pair is drawn as a band, so the width is how much of the trajectory "
      + "rests on which valuation you accept. Nine panels: the three Dell'Acqua capability scenarios "
      + "against the three measured Strömberg learning penalties, with the LaTeX tables of the "
      + "series behind them.",
  },
];

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, "data"), { recursive: true });

let html = fs.readFileSync(paths.src("simulator.html"), "utf8");

// The rewrite: every ../data/ script reference is flattened to data/, since site/ keeps
// data/ as a directory but has no parent to reach out of.
//
// Generalised over the whole prefix rather than naming one file, because naming one file
// is what broke: simulator.html gained ../data/cell-index.js and this rewrite still knew
// only about the world model, so the orphan check below — correctly — refused to publish
// a page whose second script would 404. A per-file rewrite has to be updated in lockstep
// with the page; a prefix rewrite does not.
//
// Still asserted rather than assumed. Rewriting nothing at all means the page has stopped
// reaching out of its directory, which either is a real change worth noticing or means
// this whole script is now unnecessary; either way, silence is the wrong answer.
const DATA_REF = /<script src="\.\.\/data\/([^"]+)"><\/script>/g;
const rewritten = [...html.matchAll(DATA_REF)].map((m) => m[1]);
if (!rewritten.length) {
  console.error(`[build_pages] simulator.html no longer loads anything from ../data/`);
  console.error(`  Either the data script paths changed — update ASSETS and this rewrite —`);
  console.error(`  or the page is self-contained now and build_pages.js has no job left.`);
  process.exit(1);
}
html = html.replace(DATA_REF, '<script src="data/$1"></script>');

// Every <script src> in the published page must exist in the published tree. This is
// the check that matters: the page loads its dependencies at runtime, so a missing one
// is not a build error, it is a broken site that still renders.
const referenced = [...html.matchAll(/<script src="([^"]+)"><\/script>/g)].map((m) => m[1]);
const shipped = new Set(ASSETS.map(([, dest]) => dest));
const orphans = referenced.filter((r) => !shipped.has(r));
if (orphans.length) {
  console.error(`[build_pages] the page loads scripts that are not being published: ${orphans.join(", ")}`);
  process.exit(1);
}

fs.writeFileSync(path.join(OUT, "simulator.html"), html);
ASSETS.forEach(([src, dest]) => {
  if (!fs.existsSync(src)) {
    console.error(`[build_pages] missing ${src} — run: node src/build_world_model_data.js`);
    process.exit(1);
  }
  fs.copyFileSync(src, path.join(OUT, dest));
});

// Copied with ONE rewrite, for the same reason the simulator gets one: the layouts
// differ. A report on disk sits in doc/ and reaches the simulator at
// ../src/simulator.html; on the published site both are at the root, so it is
// simulator.html. Rewriting here rather than building the reports twice — they are
// 48 MB each, and the committed copy has to stay correct for opening straight off disk,
// which is how they are read most of the time.
//
// Asserted, not assumed: a silent no-op would publish reports whose every cell click
// 404s, and a broken link inside a canvas is not something a build log would show.
const PUBLISHED_SIM_HREF = "simulator.html";
const publishedReports = REPORTS.filter((r) => fs.existsSync(r.src));
// A report may link out to its own "notes on this set" page (manifest.notesPage — see
// build_report.js) via a plain same-directory href. That page is not in REPORTS (it is
// not one of the listed entries), so without this it would silently 404 on the published
// site the moment a report that has one gets added here. Derived from the manifest
// rather than hand-listed per report, same as the report itself gets it.
const publishedNotes = [];
publishedReports.forEach((r) => {
  const body = fs.readFileSync(r.src, "utf8");
  // The value build_report.js wrote into the embedded DATA blob (--simulator-href).
  const from = /"simulatorHref":"([^"]*)"/.exec(body);
  if (!from) {
    console.error(`[build_pages] ${path.relative(paths.ROOT, r.src)} carries no simulatorHref —`
      + ` it predates --simulator-href. Rebuild it: ./src/build_reports.sh`);
    process.exit(1);
  }
  const out = from[1] === PUBLISHED_SIM_HREF
    ? body
    : body.replace(from[0], `"simulatorHref":"${PUBLISHED_SIM_HREF}"`);
  fs.writeFileSync(path.join(OUT, r.dest), out);

  const manifest = JSON.parse(fs.readFileSync(path.resolve(paths.DATA, r.manifest), "utf8"));
  if (manifest.notesPage) {
    const notesSrc = path.join(paths.DOC, manifest.notesPage.file);
    if (fs.existsSync(notesSrc)) {
      fs.copyFileSync(notesSrc, path.join(OUT, manifest.notesPage.file));
      publishedNotes.push(manifest.notesPage.file);
    } else {
      console.error(`[build_pages] note: ${path.relative(paths.ROOT, notesSrc)} not present —`
        + ` ${r.dest}'s "notes on this set" link will 404 on the published site`);
    }
  }
});
// Copied with no rewrite at all: these reach out of doc/ for nothing — no <script src>,
// no ../data/, no link to the simulator — which is the property that lets them be
// published as-is. Asserted, because a page that grew a relative reference would 404
// silently on the site while opening perfectly off disk.
const publishedDocPages = DOC_PAGES.map((d) => {
  if (!fs.existsSync(d.src)) {
    console.error(`[build_pages] missing ${path.relative(paths.ROOT, d.src)} — it is committed to the`
      + ` repository, not generated, so this is a stale entry in DOC_PAGES rather than an absent artifact`);
    process.exit(1);
  }
  const body = fs.readFileSync(d.src, "utf8");
  const reaching = [...body.matchAll(/(?:src|href)="(\.\.\/[^"]+)"/g)].map((m) => m[1]);
  if (reaching.length) {
    console.error(`[build_pages] ${path.relative(paths.ROOT, d.src)} references ${reaching.join(", ")},`
      + ` which reaches outside doc/ and will 404 once published flat. Either inline it or give this`
      + ` page a rewrite of its own, as simulator.html has.`);
    process.exit(1);
  }
  fs.copyFileSync(d.src, path.join(OUT, d.dest));
  return Object.assign({}, d, { body });
});

REPORTS.filter((r) => !fs.existsSync(r.src)).forEach((r) => {
  console.error(`[build_pages] note: ${path.relative(paths.ROOT, r.src)} not present — publishing without it`
    + ` (rebuild with ./src/build_reports.sh, which needs results/)`);
});

// --- capability-ratio (rho) sensitivity ---------------------------------------------
//
// A different shape from REPORTS above: not one self-contained file but a directory of
// per-experiment sub-reports (results/rho/<name>/rho_report.html) plus a combined index
// (results/rho/index.html) that links into them with a relative href — see
// src/rho_sensitivity.js. Preserving that same directory layout under site/rho/ is what
// keeps those links working once published.
//
// OPTIONAL, same story as the reports: built by ./src/run_rho_sensitivity.sh, which
// needs data/ (present in a fresh clone) but not results/*.csv, so it can be missing
// even when every report above is present.
//
// Only .html/.tex/.json leave results/rho/ — rho_runs.csv is the raw per-run data behind
// the reports, the same thing results/*.csv is for the reports themselves, and neither
// gets published.
const RHO_ROOT = path.join(paths.RESULTS, "rho");
const RHO_KEEP = /\.(html|tex|json)$/;
const rhoFiles = [];
if (fs.existsSync(path.join(RHO_ROOT, "index.html"))) {
  const copyKept = (srcDir, destDir) => {
    fs.mkdirSync(destDir, { recursive: true });
    fs.readdirSync(srcDir).forEach((f) => {
      const full = path.join(srcDir, f);
      if (fs.statSync(full).isFile() && RHO_KEEP.test(f)) {
        fs.copyFileSync(full, path.join(destDir, f));
        rhoFiles.push(path.relative(OUT, path.join(destDir, f)));
      }
    });
  };
  copyKept(RHO_ROOT, path.join(OUT, "rho"));
  fs.readdirSync(RHO_ROOT)
    .filter((f) => fs.statSync(path.join(RHO_ROOT, f)).isDirectory()
      && fs.existsSync(path.join(RHO_ROOT, f, "rho_report.html")))
    .sort()
    .forEach((name) => copyKept(path.join(RHO_ROOT, name), path.join(OUT, "rho", name)));
} else {
  console.error(`[build_pages] note: results/rho/index.html not present — publishing without the`
    + ` capability-ratio sensitivity pages (run ./src/run_rho_sensitivity.sh)`);
}
const rhoExperiments = rhoFiles.filter((f) => f.endsWith("/rho_report.html")).length;

// --- ACL leverage x rho sweep --------------------------------------------------------
//
// Same shape as the rho block above: a directory of per-config pages plus a combined
// index that links into them with relative hrefs, so the layout has to be preserved under
// site/acl-leverage/ for those links to resolve.
//
// OPTIONAL, same story again: built by ./src/run_acl_leverage.sh, which needs data/ but
// also 52 MB of expertise snapshots per config that are NOT in the repository, so this is
// usually absent in a fresh clone and the site publishes without it.
//
// Only .html and .json leave results/acl-leverage/. acl_grid.csv and acl_surface.csv are
// the sweep's full output tables — 1.3 MB per config, and the page recomputes everything
// they contain from the coefficients it already carries, so publishing them would add
// weight to the site without adding anything a reader can do. expertise.f32 is the raw
// population and is excluded for the same reason results/*.csv is.
const ACL_ROOT = path.join(paths.RESULTS, "acl-leverage");
const ACL_KEEP = /\.(html|json)$/;
const aclFiles = [];
if (fs.existsSync(path.join(ACL_ROOT, "index.html"))) {
  const copyKept = (srcDir, destDir) => {
    fs.mkdirSync(destDir, { recursive: true });
    fs.readdirSync(srcDir).forEach((f) => {
      const full = path.join(srcDir, f);
      // snapshots.json is the index into expertise.f32, which is not published: a reader
      // cannot use one without the other, and it is 330 KB of offsets.
      if (f === "snapshots.json") return;
      if (fs.statSync(full).isFile() && ACL_KEEP.test(f)) {
        fs.copyFileSync(full, path.join(destDir, f));
        aclFiles.push(path.relative(OUT, path.join(destDir, f)));
      }
    });
  };
  copyKept(ACL_ROOT, path.join(OUT, "acl-leverage"));
  fs.readdirSync(ACL_ROOT)
    .filter((f) => fs.statSync(path.join(ACL_ROOT, f)).isDirectory()
      && fs.existsSync(path.join(ACL_ROOT, f, "acl_leverage.html")))
    .sort()
    .forEach((name) => copyKept(path.join(ACL_ROOT, name), path.join(OUT, "acl-leverage", name)));
} else {
  console.error(`[build_pages] note: results/acl-leverage/index.html not present — publishing without`
    + ` the ACL leverage pages (run ./src/run_acl_leverage.sh)`);
}
const aclExperiments = aclFiles.filter((f) => f.endsWith("/acl_leverage.html")).length;

// --- landing page -------------------------------------------------------------------
//
// index.html USED to be the simulator itself. It is now a list, and the simulator moved
// to simulator.html — which is why PUBLISHED_SIM_HREF above says simulator.html and why
// the boot test in pages.yml names that file rather than index.html.
//
// Entries are generated from what was actually published, so a build without the reports
// lists only the simulator instead of offering three 404s. The per-set figures come from
// the manifests, not from prose here, so they cannot drift from the sets they describe.
const escapeHtml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function manifestFacts(file) {
  const m = JSON.parse(fs.readFileSync(path.resolve(paths.DATA, file), "utf8"));
  const first = m.experiments[0];
  const nx = m.studyParams[first.x].values.length, ny = m.studyParams[first.y].values.length;
  const runs = m.experiments.reduce((s, e) => s + (e.runs || 0), 0);
  return [
    m.experiments.length + " experiments",
    nx + " x " + ny + " grid",
    m.replicates + " replicates per cell",
    runs.toLocaleString("en-US") + " runs",
    // The horizon is in ticks; TICKS_PER_YEAR is 12. Stated in years because months in
    // the thousands mean nothing to a reader arriving cold.
    Math.round(m.horizon / 12) + "-year horizon",
  ];
}

const entries = [];
entries.push({
  href: "simulator.html",
  title: "Interactive simulator",
  blurb: "One run of the model, advancing a month at a time. Parameters can be changed and "
    + "the run restarted; the distribution of expertise across the population is drawn as it "
    + "moves. Cells in the pages below link into this one, set up to reproduce that cell.",
  facts: [],
});
publishedReports.forEach((r) => {
  entries.push({
    href: r.dest,
    title: r.title,
    blurb: r.blurb,
    facts: manifestFacts(r.manifest)
      .concat((fs.statSync(r.src).size / 1048576).toFixed(0) + " MB page"),
  });
});
// Facts read out of the page itself rather than typed here, for the same reason
// manifestFacts() reads the manifests: a ladder length or a shipped value written down in
// this file drifts the moment the page changes, and nothing would catch it.
function weightFacts(body, src) {
  const arr = (name) => {
    const m = new RegExp("var " + name + " = \\[([^\\]]*)\\]").exec(body);
    if (!m) {
      console.error(`[build_pages] ${path.relative(paths.ROOT, src)} no longer declares ${name} —`
        + ` update weightFacts() alongside the page`);
      process.exit(1);
    }
    return m[1].split(",").map((v) => Number(v.trim()));
  };
  const rhos = arr("RHOS"), thetas = arr("THETAS");
  const anchor = /\{ id: "p99",\s+E: ([0-9.]+)/.exec(body);
  return [
    rhos.length + " values of \u03C1 (" + rhos[0] + "\u2013" + rhos[rhos.length - 1] + ")",
    thetas.length + " values of \u03B8 (" + thetas[0] + "\u2013" + thetas[thetas.length - 1] + ")",
    "shipped \u03C1 = 1000, \u03B8 = 0.585",
    anchor ? "top 1% anchor E = " + anchor[1] : null,
  ].filter(Boolean);
}
// Same idea as weightFacts(), for the generated trajectory report. Read out of the payload
// the builder injected rather than out of the markup: that payload IS the figure's data, so
// facts taken from it cannot describe a different run than the one on the page.
function trajectoryFacts(body, src) {
  const where = path.relative(paths.ROOT, src);
  const m = /^var TRAJ = (\{.*\});$/m.exec(body);
  if (!m) {
    console.error(`[build_pages] ${where} has no single-line "var TRAJ = {...};" payload \u2014`
      + ` update trajectoryFacts() alongside valuation_trajectories.template.html`);
    process.exit(1);
  }
  let d;
  try { d = JSON.parse(m[1]); } catch (e) {
    console.error(`[build_pages] ${where}: the TRAJ payload is not parseable JSON (${e.message})`);
    process.exit(1);
  }
  if (!d.sets || !d.sets.length || !d.sets[0].configs || !d.sets[0].configs.length) {
    console.error(`[build_pages] ${where}: the TRAJ payload carries no sets with configs`);
    process.exit(1);
  }
  const s0 = d.sets[0];
  const c0 = s0.configs[0];
  const rhos = [...new Set(d.sources.reduce((a, s) => a.concat([s.lo.rho, s.hi.rho]), []))]
    .sort((a, b) => a - b);
  const horizon = c0.ticks[c0.ticks.length - 1];
  const panels = s0.configs.length * c0.gbs.length;
  return [
    panels + " panels (" + s0.configs.length + " capability scenarios \u00D7 "
      + c0.gbs.length + " learning penalties)",
    "\u03C1 " + rhos.join(", ") + " against shipped \u03C1 = " + d.shipped,
    // The gamma_above set list is the point of the page, so it is a fact rather than prose:
    // one value means the penalty applies only below the AI, two means the page carries the
    // contrast.
    d.sets.length + " \u00D7 \u03B3_above ("
      + d.sets.map((s) => s.aiDampeningAbove).join(", ") + ")",
    c0.replicates + " replicates, " + c0.ticks.length + " recorded ticks to t = " + horizon,
  ];
}

// Each page brings its own facts reader: the two pages share no structure, and one function
// probing for the other's declarations would exit the build rather than degrade.
const DOC_FACTS = {
  "capability_weight.html": weightFacts,
  "valuation_trajectories.html": trajectoryFacts,
};

// Order here is the reading order on the landing page. capability_weight says what w IS;
// valuation_trajectories says what it does over time once \u03C1 comes from a published
// valuation; the capability-ratio section below asks whether the conclusions survive
// changing \u03C1 at all.
publishedDocPages.forEach((d) => {
  const facts = DOC_FACTS[d.dest];
  if (!facts) {
    console.error(`[build_pages] DOC_PAGES lists ${d.dest} but DOC_FACTS has no reader for it \u2014`
      + ` add one, or the landing entry would ship with no facts`);
    process.exit(1);
  }
  entries.push({ href: d.dest, title: d.title, blurb: d.blurb, facts: facts(d.body, d.src) });
});

if (rhoExperiments) {
  // Facts pulled from the first summary found rather than hardcoded — same reasoning as
  // manifestFacts() above: a rho list or config count typed here would drift the moment
  // a rerun changed it.
  const firstSummary = fs.readdirSync(RHO_ROOT)
    .map((f) => path.join(RHO_ROOT, f, "rho_summary.json"))
    .find((f) => fs.existsSync(f));
  const s = firstSummary ? JSON.parse(fs.readFileSync(firstSummary, "utf8")) : null;
  entries.push({
    href: "rho/index.html",
    title: "Capability-ratio sensitivity",
    blurb: "Every capability number above rests on ρ, a stated assumption — not a measured "
      + "one — about how much more a ceiling performer is worth than someone who merely "
      + "qualifies as expert. This re-examines a representative pairing from every set above "
      + "across a range of ρ, to see whether the reported conclusions hold or only the "
      + "shipped value's numbers do.",
    facts: [
      rhoExperiments + " experiments re-examined",
      s ? (s.rhos.length + " values of ρ (" + s.rhos[0] + "–" + s.rhos[s.rhos.length - 1] + ")") : null,
      s ? ("shipped ρ = " + s.shippedRho) : null,
    ].filter(Boolean),
  });
}

if (aclExperiments) {
  // Facts from the index's own data block rather than typed here — the sweep's grid and
  // rho range are command-line options, so anything hardcoded would drift the first time
  // someone re-swept with different ones.
  let s2 = null;
  try {
    const src = fs.readFileSync(path.join(ACL_ROOT, "index.html"), "utf8");
    s2 = JSON.parse(/window\.ACL_INDEX = (\{[\s\S]*?\});<\/script>/.exec(src)[1]);
  } catch (e) { /* index present but unreadable — list it without the facts line */ }
  entries.push({
    href: "acl-leverage/index.html",
    title: "Where AI is a net gain in capability",
    blurb: "The Dell'Acqua leverage parameters — what AI adds to weaker performers inside "
      + "its frontier, what it adds to stronger ones, and what it costs those who cannot "
      + "tell its work is wrong — are four numbers from one study of one profession on one "
      + "model generation. These pages sweep all three against ρ, to show where the system "
      + "ends up with more capability than it had without AI, and where that answer depends "
      + "on an assumption rather than on a measurement.",
    facts: [
      aclExperiments + " experiments swept",
      s2 ? (s2.grid.g_n.length + "×" + s2.grid.g_x.length + "×" + s2.grid.d_n.length
        + " leverage grid") : null,
      s2 ? ("ρ " + s2.rhoRange[0] + "–" + s2.rhoRange[1]) : null,
      "no simulation re-run per parameter point",
    ].filter(Boolean),
  });
}

{
  const templatePath = paths.src("landing.template.html");
  let landing = fs.readFileSync(templatePath, "utf8");
  ["<!--__PAGES__-->", "<!--__FOOTER__-->"].forEach((marker) => {
    if (!landing.includes(marker)) {
      console.error(`[build_pages] landing.template.html is missing the ${marker} marker`);
      process.exit(1);
    }
  });
  const items = entries.map((e) =>
    '    <li>\n'
    + '      <a href="' + e.href + '">' + escapeHtml(e.title) + "</a>\n"
    + "      <p>" + escapeHtml(e.blurb) + "</p>\n"
    + (e.facts.length ? '      <p class="facts">' + escapeHtml(e.facts.join("  \u00b7  ")) + "</p>\n" : "")
    + "    </li>").join("\n");
  // Build date, not a version: the reports are generated artifacts and the only honest
  // thing to say about them is when they were last assembled.
  const footer = "    Site assembled " + new Date().toISOString().slice(0, 10)
    + ". The pages listed above are generated from simulation output and are static;"
    + " each carries its own generation date."
    + (publishedReports.length < REPORTS.length
      ? " " + (REPORTS.length - publishedReports.length) + " report(s) were not present at build time."
      : "")
    + (rhoExperiments ? "" : " The capability-ratio sensitivity pages were not present at build time.");
  landing = landing.replace("<!--__PAGES__-->", items).replace("<!--__FOOTER__-->", footer);
  fs.writeFileSync(path.join(OUT, "index.html"), landing);
}

// Without this, Pages runs the tree through Jekyll, which ignores files and folders
// beginning with an underscore and can rewrite what it thinks is templating.
fs.writeFileSync(path.join(OUT, ".nojekyll"), "");

const published = [["index.html"], ["simulator.html"], ...ASSETS.map(([, d]) => [d]),
  ...publishedReports.map((r) => [r.dest]), ...publishedNotes.map((f) => [f]), ...rhoFiles.map((f) => [f])];
const total = published.reduce((s, [f]) => s + fs.statSync(path.join(OUT, f)).size, 0);
console.log(`wrote site/ — ${published.length} files, ${(total / 1048576).toFixed(1)} MB`);
console.log(`  index.html  (landing page, ${entries.length} entries)`);
console.log(`  simulator.html  (simulator.html, ${rewritten.length} ../data/ path(s) flattened: ${rewritten.join(", ")})`);
ASSETS.forEach(([, d]) => console.log(`  ${d}`));
publishedReports.forEach((r) =>
  console.log(`  ${r.dest}  (${r.title}, ${(fs.statSync(r.src).size / 1048576).toFixed(0)} MB)`));
publishedNotes.forEach((f) => console.log(`  ${f}  (notes page)`));
publishedDocPages.forEach((d) => console.log(`  ${d.dest}  (${d.title}, written)`));
if (rhoExperiments) console.log(`  rho/  (capability-ratio sensitivity, ${rhoExperiments} experiment(s), ${rhoFiles.length} files)`);
if (aclExperiments) console.log(`  acl-leverage/  (leverage x rho sweep, ${aclExperiments} experiment(s), ${aclFiles.length} files)`);
console.log(`\npreview locally:  npx serve site    (or: cd site && python3 -m http.server)`);
