// Assembles site/ — a self-contained copy of the simulator ready for GitHub Pages.
//
//   node src/build_pages.js
//
// The simulator is already a static page with no build step, so this exists for one
// reason: it loads ../data/world-model-data.js, a path that reaches OUT of the
// directory it sits in. Publishing src/ alone would silently drop the world model and
// leave the page on the generated BA graph — it degrades rather than failing, which is
// the worst way for this to go wrong. The copy flattens that one path.
//
// Deliberately NOT publishing the whole repository root. That would work (the relative
// paths resolve as-is) but the entry point would be /src/simulator.html and every
// source file would be served alongside it. Four files and an index.html is a smaller
// thing to reason about.
"use strict";
const fs = require("fs");
const path = require("path");
const paths = require("./paths.js");

const OUT = path.join(paths.ROOT, "site");

// [source, destination]. Destinations are flat except for data/, which is kept as a
// directory so the rewrite below is one path rather than several.
const ASSETS = [
  [paths.src("engine.js"), "engine.js"],
  [paths.src("world_model.js"), "world_model.js"],
  [paths.data("world-model-data.js"), "data/world-model-data.js"],
  // The cell-code lookup behind simulator.html's applyScenarioCode() — typing "AI-482"
  // reproduces that heatmap cell. Generated by build_report.js, so it changes whenever
  // an experiment set is rebuilt; published rather than inlined for that reason.
  [paths.data("cell-index.js"), "data/cell-index.js"],
];

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, "data"), { recursive: true });

let html = fs.readFileSync(paths.src("simulator.html"), "utf8");

// The rewrite: every ../data/ script reference is flattened to data/, since site/ keeps
// data/ as a directory but has no parent to reach out of.
//
// Generalised over the whole prefix rather than naming one file, because naming one file
// is what broke: simulator.html gained ../data/cell-index.js and this rewrite still knew
// only about the world model, so the orphan check below — correctly — refused to publish
// a page whose second script would 404. A per-file rewrite has to be updated in lockstep
// with the page; a prefix rewrite does not.
//
// Still asserted rather than assumed. Rewriting nothing at all means the page has stopped
// reaching out of its directory, which either is a real change worth noticing or means
// this whole script is now unnecessary; either way, silence is the wrong answer.
const DATA_REF = /<script src="\.\.\/data\/([^"]+)"><\/script>/g;
const rewritten = [...html.matchAll(DATA_REF)].map((m) => m[1]);
if (!rewritten.length) {
  console.error(`[build_pages] simulator.html no longer loads anything from ../data/`);
  console.error(`  Either the data script paths changed — update ASSETS and this rewrite —`);
  console.error(`  or the page is self-contained now and build_pages.js has no job left.`);
  process.exit(1);
}
html = html.replace(DATA_REF, '<script src="data/$1"></script>');

// Every <script src> in the published page must exist in the published tree. This is
// the check that matters: the page loads its dependencies at runtime, so a missing one
// is not a build error, it is a broken site that still renders.
const referenced = [...html.matchAll(/<script src="([^"]+)"><\/script>/g)].map((m) => m[1]);
const shipped = new Set(ASSETS.map(([, dest]) => dest));
const orphans = referenced.filter((r) => !shipped.has(r));
if (orphans.length) {
  console.error(`[build_pages] the page loads scripts that are not being published: ${orphans.join(", ")}`);
  process.exit(1);
}

fs.writeFileSync(path.join(OUT, "index.html"), html);
ASSETS.forEach(([src, dest]) => {
  if (!fs.existsSync(src)) {
    console.error(`[build_pages] missing ${src} — run: node src/build_world_model_data.js`);
    process.exit(1);
  }
  fs.copyFileSync(src, path.join(OUT, dest));
});

// Without this, Pages runs the tree through Jekyll, which ignores files and folders
// beginning with an underscore and can rewrite what it thinks is templating.
fs.writeFileSync(path.join(OUT, ".nojekyll"), "");

const total = [["index.html"], ...ASSETS.map(([, d]) => [d])]
  .reduce((s, [f]) => s + fs.statSync(path.join(OUT, f)).size, 0);
console.log(`wrote site/ — ${referenced.length + 1} files, ${(total / 1024).toFixed(0)} KB`);
console.log(`  index.html  (simulator.html, ${rewritten.length} ../data/ path(s) flattened: ${rewritten.join(", ")})`);
ASSETS.forEach(([, d]) => console.log(`  ${d}`));
console.log(`\npreview locally:  npx serve site    (or: cd site && python3 -m http.server)`);
